// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    IconMdiAccount: typeof import('virtual:vite-icons/mdi/account')['default']
    IconMdiAccountClockOutline: typeof import('virtual:vite-icons/mdi/account-clock-outline')['default']
  }
}

export { }
