// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    PageContainer: typeof import('D:/Projects/gopowerteam/quickstart.vue3-web-template/src/shared/components/page-container.vue')['default']
    SiderBar: typeof import('D:/Projects/gopowerteam/quickstart.vue3-web-template/src/layouts/components/sider-bar.vue')['default']
    SiderMenu: typeof import('D:/Projects/gopowerteam/quickstart.vue3-web-template/src/layouts/components/sider-menu.vue')['default']
    SiderPanel: typeof import('D:/Projects/gopowerteam/quickstart.vue3-web-template/src/layouts/components/sider-panel.vue')['default']
    SiderTool: typeof import('D:/Projects/gopowerteam/quickstart.vue3-web-template/src/layouts/components/sider-tool.vue')['default']
  }
}

export { }
