/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'poster-download-record'
const service = 'xbt-platform-material-service'

export const PosterDownloadRecordController = {
    // 创建
    create: {
        service,
        controller,
        path: '/api/posterDownloadRecord/create',
        action: 'create',
        type: RequestMethod.Post
    },
    // 查询全部
    getAll: {
        service,
        controller,
        path: '/api/posterDownloadRecord/getAll',
        action: 'getAll',
        type: RequestMethod.Get
    },
    // 使用ID查询
    getById: {
        service,
        controller,
        path: '/api/posterDownloadRecord/getById/{id}',
        action: 'getById',
        type: RequestMethod.Get
    },
    // 分页查询
    query: {
        service,
        controller,
        path: '/api/posterDownloadRecord/query',
        action: 'query',
        type: RequestMethod.Get
    },
    // 通过海报ID分页查询
    queryByPoster: {
        service,
        controller,
        path: '/api/posterDownloadRecord/queryByPoster',
        action: 'queryByPoster',
        type: RequestMethod.Get
    },
    // 通过海报ID查询下载数量
    queryCountByPoster: {
        service,
        controller,
        path: '/api/posterDownloadRecord/queryCountByPoster/{posterId}',
        action: 'queryCountByPoster',
        type: RequestMethod.Get
    }
}
