/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { PosterDownloadRecordController } from '@/http/controller/material-service/poster-download-record.controller'

export class PosterDownloadRecordService {
    /**
     * 创建
     */
    @Request({
        server: PosterDownloadRecordController.create
    })
    public create(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 查询全部
     */
    @Request({
        server: PosterDownloadRecordController.getAll
    })
    public getAll(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 使用ID查询
     */
    @Request({
        server: PosterDownloadRecordController.getById
    })
    public getById(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 分页查询
     */
    @Request({
        server: PosterDownloadRecordController.query
    })
    public query(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 通过海报ID分页查询
     */
    @Request({
        server: PosterDownloadRecordController.queryByPoster
    })
    public queryByPoster(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 通过海报ID查询下载数量
     */
    @Request({
        server: PosterDownloadRecordController.queryCountByPoster
    })
    public queryCountByPoster(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
