/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { AppController } from '@/http/controller/authorization-service/app.controller'

export class AppService {
  /**
   * 获取扫码登录地址
   */
  @Request({
    server: AppController.getQrConnectUrl,
  })
  public getQrConnectUrl(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
  /**
   * 获取授权路径
   */
  @Request({
    server: AppController.authorize,
  })
  public authorize(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
  /**
   * 获取JSConfig配置
   */
  @Request({
    server: AppController.jsConfig,
  })
  public jsConfig(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
  /**
   * 获取App配置
   */
  @Request({
    server: AppController.getConfig,
  })
  public getConfig(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
}
