/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { StorageController } from '@/http/controller/authorization-service/storage.controller'

export class StorageService {
  /**
   * 获取文件存储配置
   */
  @Request({
    server: StorageController.getStorageConfig,
  })
  public getStorageConfig(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
  /**
   * 获取文件存储授权
   */
  @Request({
    server: StorageController.getStorageCredential,
  })
  public getStorageCredential(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
  /**
   * 获取文件授权地址
   */
  @Request({
    server: StorageController.getObjectUrl,
  })
  public getObjectUrl(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
}
